version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
        - 6379

  server:
    container_name: consultant-dev
    image: consultant-dev
    build: ../
    ports:
      - "8000:8000"
    depends_on:
      - "redis"

networks:
  default:
    external:
      name: consultantdev